export const permissionCatalog = [
  { key: "panel.access", label: "Acceso al panel", category: "Paneles / vistas" },
  { key: "finance.view", label: "Ver finanzas", category: "Paneles / vistas" },
  { key: "egresos.view", label: "Ver egresos", category: "Paneles / vistas" },
  { key: "consumo.view", label: "Ver consumo electrico", category: "Paneles / vistas" },
  { key: "gestion.view", label: "Ver gestion", category: "Paneles / vistas" },
  { key: "usuarios.view", label: "Ver usuarios", category: "Paneles / vistas" },
  { key: "info.view", label: "Ver informacion", category: "Paneles / vistas" },
  { key: "reclamos.view", label: "Ver reclamos asignados", category: "Paneles / vistas" },
  { key: "comunidad.manage", label: "Gestionar comunidad", category: "Paneles / vistas" },
  { key: "seguridad.view", label: "Ver seguridad", category: "Paneles / vistas" },
  { key: "archivo.finance.view", label: "Ver archivo financiero", category: "Paneles / vistas" },
  { key: "archivo.seguridad.view", label: "Ver archivo de seguridad", category: "Paneles / vistas" },
  { key: "finance.vecinos.edit", label: "Editar vecinos", category: "Finanzas" },
  { key: "finance.payments.approve", label: "Aprobar pagos", category: "Finanzas" },
  { key: "finance.payments.reject", label: "Rechazar pagos", category: "Finanzas" },
  { key: "finance.prices.edit", label: "Editar precios", category: "Finanzas" },
  { key: "finance.cuota_details.edit", label: "Editar detalle de cuota", category: "Finanzas" },
  { key: "egresos.create", label: "Añadir egresos", category: "Egresos" },
  { key: "egresos.manage", label: "Gestionar egresos", category: "Egresos" },
  { key: "consumo.manage", label: "Gestionar consumo electrico", category: "Consumo electrico" },
  { key: "seguridad.novedades.manage", label: "Gestionar novedades de seguridad", category: "Seguridad" },
  { key: "seguridad.ingresantes.manage", label: "Gestionar ingresantes", category: "Seguridad" },
  { key: "seguridad.recorridos.manage", label: "Gestionar recorridos", category: "Seguridad" },
  { key: "seguridad.calendar.manage", label: "Gestionar calendario de seguridad", category: "Seguridad" },
  { key: "info.recordatorios.manage", label: "Gestionar recordatorios", category: "Informacion" },
  { key: "info.novedades.manage", label: "Gestionar novedades", category: "Informacion" },
  { key: "info.calendar.manage", label: "Gestionar calendario", category: "Informacion" },
  { key: "info.biblioteca.manage", label: "Gestionar biblioteca digital", category: "Informacion" },
  { key: "reclamos.feed.view", label: "Ver feed de reclamos", category: "Reclamos" },
  { key: "reclamos.manage", label: "Gestionar reclamos", category: "Reclamos" },
  { key: "comunidad.votacion.delete_others", label: "Eliminar votaciones de otros", category: "Comunidad" },
  { key: "comunidad.solicitudes.manage", label: "Gestionar solicitudes", category: "Comunidad" },
  { key: "notifications.create", label: "Crear notificaciones", category: "Notificaciones" },
  { key: "notifications.receive.price_change", label: "Recibir cambios de cuota", category: "Notificaciones" },
  { key: "notifications.receive.new_invoice", label: "Recibir estados de cuenta", category: "Notificaciones" },
  { key: "notifications.receive.new_recordatorio", label: "Recibir recordatorios", category: "Notificaciones" },
  { key: "notifications.receive.new_novedad", label: "Recibir novedades", category: "Notificaciones" },
  { key: "notifications.receive.new_calendar_event", label: "Recibir eventos de calendario", category: "Notificaciones" },
  { key: "notifications.receive.payment_request", label: "Recibir solicitudes de pago", category: "Notificaciones" },
  { key: "notifications.receive.payment_approved", label: "Recibir pagos aprobados", category: "Notificaciones" },
  { key: "notifications.receive.payment_rejected", label: "Recibir pagos rechazados", category: "Notificaciones" },
  { key: "notifications.receive.new_signup_request", label: "Recibir solicitudes de cuenta", category: "Notificaciones" },
  { key: "notifications.receive.new_complaint", label: "Recibir reclamos nuevos", category: "Notificaciones" },
  { key: "notifications.receive.reclamo_status_change", label: "Recibir cambios de reclamos propios", category: "Notificaciones" },
  { key: "notifications.receive.visita_status_change", label: "Recibir avisos de visitas", category: "Notificaciones" },
  { key: "notifications.receive.new_visit_request", label: "Recibir solicitudes de visita", category: "Notificaciones" },
  { key: "users.approve", label: "Aprobar usuarios", category: "Usuarios y roles" },
  { key: "users.reject", label: "Rechazar usuarios", category: "Usuarios y roles" },
  { key: "users.delete", label: "Eliminar usuarios", category: "Usuarios y roles" },
  { key: "users.role.change", label: "Cambiar rol de usuarios", category: "Usuarios y roles" },
  { key: "users.profile.edit", label: "Editar perfil de usuarios", category: "Usuarios y roles" },
  { key: "users.admin_notes.view", label: "Ver notas administrativas", category: "Usuarios y roles" },
  { key: "users.admin_notes.edit", label: "Editar notas administrativas", category: "Usuarios y roles" },
  { key: "roles.manage", label: "Gestionar roles", category: "Usuarios y roles" },
] as const;

export type PermissionKey = (typeof permissionCatalog)[number]["key"];

export const permissionKeys = permissionCatalog.map((permission) => permission.key) as PermissionKey[];
